# Generated by Django 3.2.13 on 2023-11-07 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appdearte', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='title',
            new_name='name',
        ),
    ]
