# Generated by Django 3.2.13 on 2023-11-14 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdearte', '0003_auto_20231114_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='hour',
            field=models.CharField(choices=[('M', 'Manhã'), ('T', 'Tarde'), ('N', 'Noite')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
