# Generated by Django 3.2.13 on 2023-11-14 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdearte', '0004_auto_20231114_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='price',
            field=models.CharField(choices=[('G', 'Gratuito'), ('1', 'R$10-R$20'), ('2', 'R$20-R$40'), ('3', 'R$40-')], max_length=1, null=True),
        ),
    ]
