# Generated by Django 3.2.13 on 2023-11-20 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdearte', '0005_alter_events_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(choices=[('G', 'Gratuito'), ('1', 'R$10-R$20'), ('2', 'R$20-R$40'), ('3', 'R$40-')], max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='events',
            name='hour',
        ),
        migrations.RemoveField(
            model_name='events',
            name='category',
        ),
        migrations.AlterField(
            model_name='events',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.RemoveField(
            model_name='events',
            name='price',
        ),
        migrations.AddField(
            model_name='events',
            name='time',
            field=models.ManyToManyField(to='appdearte.Time'),
        ),
        migrations.AddField(
            model_name='events',
            name='category',
            field=models.ManyToManyField(to='appdearte.Category'),
        ),
        migrations.AddField(
            model_name='events',
            name='price',
            field=models.ManyToManyField(to='appdearte.Price'),
        ),
    ]
