# Generated by Django 3.2.13 on 2023-11-20 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdearte', '0006_auto_20231120_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='link',
            field=models.URLField(blank=True),
        ),
    ]
