# Generated by Django 3.2.13 on 2023-11-28 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdearte', '0007_events_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recomendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recomendation', models.CharField(choices=[('1', 'Horrível'), ('2', 'Meh'), ('3', 'Bom'), ('4', 'Ótimo'), ('5', 'Excelente')], max_length=1, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='events',
            name='recomendation',
            field=models.ManyToManyField(to='appdearte.Recomendation'),
        ),
    ]
