# Generated by Django 3.2.13 on 2023-11-28 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdearte', '0008_auto_20231128_0115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='recomendation',
        ),
        migrations.AddField(
            model_name='events',
            name='recomendation',
            field=models.CharField(choices=[('1', 'Horrível'), ('2', 'Meh'), ('3', 'Bom'), ('4', 'Ótimo'), ('5', 'Excelente')], max_length=1, null=True),
        ),
        migrations.DeleteModel(
            name='Recomendation',
        ),
    ]
