# Generated by Django 3.2.13 on 2023-11-28 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdearte', '0009_auto_20231128_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='recomendation',
            field=models.CharField(choices=[('1', '1 estrela'), ('2', '2 estrela'), ('3', '3 estrela'), ('4', '4 estrela'), ('5', '5 estrela')], max_length=1, null=True),
        ),
    ]
